project:
  type: website
  output-dir: docs
  
website:
  title: "Occupancy Models with R-INLA"
  navbar:
    left:
      - href: index.qmd
        text: Fitting Occupancy models with INLA
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/JBelmont89/Occupancy-Models-in-INLA/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, YOUR NAME"

format:
  html:
    theme: cerulean
    toc: true
  pdf: default

editor: source

